apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: rtf
  labels:
    app: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: sample-controller
          image: sample-controller
          ports:
            - name: http
              containerPort: 1338