apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: rtfwebhookmutate
  labels:
    app: rtfwebhookmutate
webhooks:
  - name: rtf-webhook.sample-admission-controller-git.svc
    admissionReviewVersions: ["v1", "v1beta1"]
    matchPolicy: Equivalent
    namespaceSelector:
    clientConfig:
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZNakNDQXhxZ0F3SUJBZ0lKQUp1WkREbWIwRGlkTUEwR0NTcUdTSWIzRFFFQkN3VUFNRU14UVRBL0JnTlYKQkFNTU9ITmhiWEJzWlMxaFpHMXBjM05wYjI0dFkyOXVkSEp2Ykd4bGNpMW5hWFF1WVdSdGFYTnphVzl1TFdOdgpiblJ5YjJ4c1pYSXVjM1pqTUI0WERUSXpNRFV5TmpBd05EQTFPVm9YRFRJME1EVXlOVEF3TkRBMU9Wb3dRekZCCk1EOEdBMVVFQXd3NGMyRnRjR3hsTFdGa2JXbHpjMmx2YmkxamIyNTBjbTlzYkdWeUxXZHBkQzVoWkcxcGMzTnAKYjI0dFkyOXVkSEp2Ykd4bGNpNXpkbU13Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQ0R3QXdnZ0lLQW9JQwpBUURQcEMyVXRnQ2RuODh5UFVNeVpzbUszK25KMm5VM1RTOGFjVzlyS1lkSjlBMXFDZDNzalkwaXE5YTFCNEZiCnNkajVCSllJMkNUc1hLazFNZWkvdFo4dC82aG05MTErWmpxMmx6ekxTRU12bTJWY0NwWHpwaXNlcThzQkVmU0YKR2ZpWFJRbVA3NTEzVStER0F3NkRNNEpqTDJ2Mzk0dGl4dHljaXFyT1NndHVwTEF0Mnd2SmdHd25Mc2pva1FkMwplWW1FN1JZMzVIUFdoZEhIYUIzckFybXRRempuc0FXS0QrVVptNDJndnkvUWZkVTBNTlorNkNickE4Q3REOEZWCkRkMDEwbU5yc0xvenY0L1ZvVkF2eXRYbjQvbnJOVXZqMjZ4dXRMQi8rSS90Q3FneDl2dGFoTk5hRzhHWnRJR0IKNFR3UW1XbkZCV2xGUm44alBqenE0NkhIYTYzYWQ2YnNXL2JWSFQ4MWw4N1daV2RPVzRPY0pKTDRzaTgxM2ZobgpnVFFnTms2NzY3NVY1N204cEJrKytrUyt5dVc3RTl6L01Eci9CMlM2VC81dTdiMC9iSlVaaEY5OWNndU1WUXQ5CndiMnlwRGY1b1FRanRCTVhxVFFIeEg0RzZGc0FST29TcVg4amthWG9VdHdHc293ZFNGMFhRT0R0NmtQclNJeEQKeUgweGVsek8rSmdHWjRsc0RWcWp1L2Z3dEVlWXRvTW1weXRKTTI5aFZaaytxQ2QrMDkwMWNEeTFBV205WUlnWQo4Y2pKV3ptaHR3U3VnUmQ1akJKaUduSS9zaExxWmhrWi94MVN4bFdyOGVpU25kK1FHUmhZaHVDS25kU1AwMHRrCm4wOTg2R1gvMlN1RUJZYVlVQ3A4QXdrUTZvL21NZnc3UWswcXhkVkgxZ0wxTFFJREFRQUJveWt3SnpBbEJnTlYKSFJFRUhqQWNnaG9xTG1Ga2JXbHpjMmx2YmkxamIyNTBjbTlzYkdWeUxuTjJZekFOQmdrcWhraUc5dzBCQVFzRgpBQU9DQWdFQXRiRTBUckJhdGFPOXV6ODkvYUdjaW5mZm9XUkxVNExuMGVmZG5UdXNocUZZQVI4NGdmcXpJZFBmCldJbzRQRVdibEt4MVV5YUVEelRIMVdocjJtdTdJcEpLRCtuOFIyampCWXBzd29HMU85SytxbDhSRklOY1VJaVoKa0JnM001a1lmeE4wa1cyZTJ3MFRTbGFxU1BXeVBWdWdMU3ZUaTJ6Z0x2VDRJdlV2VjN4bEhFeFhPWVJYQ1hXNAp4UEswbDFRcXFlWnJ0c3ZlS3RFVTcyb2hQWmRpWTdZZnBHY1I1WEw3K3VLWFo1RTllWGx5ajhFUWVrd2RwMzhoCm40dFlXbnNLMWZUOEdJcTAxbDBFN0Y0RDFIbTFOQlZML3NCdHdkbU1VbG9SK2YzZklkMFh1VG5BOS9ncHJvcXQKejlRMlJUNi9ZZXd4YVBMZDJMTFcrb3dHVUxVbXdOVk9MQ0dvUWl6UXczTXJyTllMMTdWNGFXRDJIejVoYkJwOQp1ZkdhYVZnd2xIQ25LeEM2OFJ4cFRHTnJmOXdkTXYrMVBXM043MVFRTEJ6eVN6dDNMT0NDRTZsVFRZcUNOZGduCnZRWEduWUVtY3p3ekVvNlpBUFNuOFVWbUQ5VHRYMEFpKzFvbllianBMUXJreTZRU05FMkd4Qk9Pd3haZWRnK3cKUlVFeWMwSW5ZemUvMnpLWElJUGZCYW13NlRHdnVTei9BR0loNE5rVWdNN3J6WUpZWExEYzZxSHRIRFNjMVdFNAp1dGt2ak1NMVY2YjZoQ3VXN1o2RTJrK28rSFUxN2JkdEliN1BwZE1XckxyWSt1bkRWTXlBZ3hqcnV1YVpNbUtFCnpLaG90cWN1YzJES3g1NWdHbnhmVEpiMGJvdHJ3ekRCcEhTUkVjazhGN0ZvYWVYZ1RCMD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="
      service:
        namespace: admission-controller
        name: sample-admission-controller-git
        path: /mutate
        port: 8080
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["*"]
        resources: ["pods"]
        scope: "*"
    sideEffects: None
    timeoutSeconds: 10
